path = "C:\\Program Files (x86)\\Steam\\steamapps\\workshop\\content\\304930\\3097786894\\advancedgrenades"

[workshop]
id = 3097786894
name = "Advanced Grenades"
authors = ["biedaktokox", "Dizzpie"]
