path = "C:\\Program Files (x86)\\Steam\\steamapps\\workshop\\content\\304930\\3000549606\\Buak\\Bundles"

[workshop]
id = 3000549606
name = "Buak"
authors = ["Toothy Deerryte", "staswalle", "Paulfest"]
