path = "C:\\Program Files (x86)\\Steam\\steamapps\\workshop\\content\\304930\\3251926587\\Escalation\\Bundles"

[workshop]
id = 3251926587
authors = ["Witness Protection", "Renaxon", "dug", "NSTM"]
name = "Escalation"
